/** V1 OPEN_TPL 이식 — OFD_신규매장_오픈_매뉴얼.xlsx 기반 54항목.
 * offset: 오픈일 기준 데드라인(일). 명시 데드라인이 있으면 그 값, 없으면 단계 기본값. */
export interface OpeningTemplateItem {
  phase: OpeningPhase; group: string; title: string;
  owner: "hq" | "pt" | "both"; offset: number; storeType: string | null; detail: string;
}
export const OPENING_PHASES = ["D-4주차", "D-3주차", "D-2주차", "D-1주차", "D-DAY"] as const;
export type OpeningPhase = (typeof OPENING_PHASES)[number];
export const OPENING_TEMPLATE: readonly OpeningTemplateItem[] = [
  { phase: "D-4주차", group: "초기 구성", title: "입점위치 확인·상권 파악", owner: "both", offset: -28, storeType: null, detail: "매장유형(테이블형/포장형) 선정 · 기물리스트 선정 · 평면 구성" },
  { phase: "D-4주차", group: "초기 구성", title: "도넛 판매유형·납품처 지정", owner: "hq", offset: -28, storeType: null, detail: "생산형: 생산실 평수 확인 / 납품형: 납품 가능 생산팀 지정" },
  { phase: "D-4주차", group: "초기 구성", title: "위생교육 수료", owner: "pt", offset: -28, storeType: null, detail: "영업신고 전 필수" },
  { phase: "D-4주차", group: "초기 구성", title: "영업신고증 발급", owner: "pt", offset: -10, storeType: null, detail: "오픈일 기준 10일 전까지 준비" },
  { phase: "D-4주차", group: "초기 구성", title: "사업자등록증 발급", owner: "pt", offset: -10, storeType: null, detail: "오픈일 기준 10일 전까지 준비" },
  { phase: "D-4주차", group: "초기 구성", title: "예상 고객층 파악 · 메뉴/객단가 선정", owner: "hq", offset: -28, storeType: null, detail: "적용 가능한 프로모션 기획 포함" },
  { phase: "D-4주차", group: "초기 구성", title: "[테이블형] 반자동 머신·시그니처 음료 구성", owner: "hq", offset: -28, storeType: "테이블형", detail: "커피 퀄리티 교육 계획 · 비주얼 시그니처 음료 · 차분한 서비스 톤" },
  { phase: "D-4주차", group: "초기 구성", title: "[포장형] 자동머신·밀크/슬러시 · 타임세일 기획", owner: "hq", offset: -28, storeType: "포장형", detail: "출퇴근·점심 타임세일 · 미리 포장 가능한 메뉴 위주 구성 (오피스/메디컬·역세권 상권)" },
  { phase: "D-4주차", group: "대형기물 발주", title: "대형기물 리스트업", owner: "hq", offset: -28, storeType: null, detail: "도넛 판매유형에 따라 리스트업" },
  { phase: "D-4주차", group: "대형기물 발주", title: "업체 선정", owner: "hq", offset: -28, storeType: null, detail: "" },
  { phase: "D-4주차", group: "대형기물 발주", title: "대형기물 발주 요청", owner: "pt", offset: -28, storeType: null, detail: "" },
  { phase: "D-4주차", group: "스텝 채용", title: "채용 공고 게시", owner: "pt", offset: -28, storeType: null, detail: "상시 채용" },
  { phase: "D-4주차", group: "스텝 채용", title: "면접 진행·채용인원 확정", owner: "pt", offset: -28, storeType: null, detail: "테이블형: 총 4~5명(관리자1·직원3~4·알바) / 포장형: 총 2~4명(관리자1·직원1~2·알바) · 예비인력까지 면접 · 교육기간 근무 가능여부 확인" },
  { phase: "D-4주차", group: "교육", title: "교육 지점 선정·일정 조율", owner: "hq", offset: -28, storeType: null, detail: "테이블형: 한남·가로수길 / 포장형: 용산·정자·사당 — 각 지점 점장과 일정 조율" },
  { phase: "D-4주차", group: "교육", title: "교육 지점에 교육 매뉴얼 전달", owner: "hq", offset: -28, storeType: null, detail: "" },
  { phase: "D-4주차", group: "교육", title: "유니폼 발주·교육 지점 분배", owner: "pt", offset: -28, storeType: null, detail: "" },
  { phase: "D-4주차", group: "교육", title: "관리자 교육 시작", owner: "pt", offset: -28, storeType: null, detail: "최소 2개 지점 · 3~4주(실근무 약 20일) · 커리큘럼: 1주 서비스/위생/포장법 → 2주 홀관리/음료/커피 → 3주 클레임/수량관리(매장·배달 비율, 폐기) → 4주 운영매뉴얼·인수인계" },
  { phase: "D-3주차", group: "교육", title: "직원(스텝) 교육 시작", owner: "pt", offset: -21, storeType: null, detail: "1개 지점 · 1~3주(실근무 약 15일) · 메뉴숙지/포장법/고객응대 → 커피셋팅/음료제조 · 서비스 집중교육(클레임 응대·상황 대처)" },
  { phase: "D-3주차", group: "서류 준비", title: "매장 비치 서류 준비", owner: "hq", offset: -21, storeType: null, detail: "서비스매뉴얼 · 음료레시피 · 위생 체크리스트 · 발주 체크리스트" },
  { phase: "D-3주차", group: "서류 준비", title: "근로계약서 작성", owner: "pt", offset: -21, storeType: null, detail: "근무시작 1주일 내 — 교육지점 점장 또는 운영지원팀" },
  { phase: "D-3주차", group: "서류 준비", title: "보건증 발급·유효기간 확인", owner: "pt", offset: -14, storeType: null, detail: "실전 투입 최소 2주 전 — 채용 스텝 전원 확인/재발급" },
  { phase: "D-2주차", group: "발주", title: "소기물 발주", owner: "pt", offset: -14, storeType: null, detail: "본사 리스트업(메뉴 기준 업데이트) 후 발주 요청" },
  { phase: "D-2주차", group: "발주", title: "부자재 발주", owner: "pt", offset: -14, storeType: null, detail: "제작비품·굿즈 등 · 내정 관리자 있을 시 발주 교육 병행" },
  { phase: "D-2주차", group: "발주", title: "생활용품·사무용품 발주", owner: "pt", offset: -14, storeType: null, detail: "화장실 관리 여부 확인 포함" },
  { phase: "D-2주차", group: "발주", title: "청소용품 발주", owner: "pt", offset: -14, storeType: null, detail: "" },
  { phase: "D-2주차", group: "디자인물", title: "디자인물 리스트업·출력 요청", owner: "hq", offset: -14, storeType: null, detail: "매장 상황에 따라 디자인팀 수정 요청" },
  { phase: "D-2주차", group: "디자인물", title: "오픈일정 포스터 제작", owner: "hq", offset: -14, storeType: null, detail: "내용 정리 후 디자인팀 요청" },
  { phase: "D-2주차", group: "디자인물", title: "디자인물 후작업", owner: "hq", offset: -14, storeType: null, detail: "코팅 · 스탠드 · POP 체크" },
  { phase: "D-2주차", group: "디자인물", title: "[테이블형] 디자인물 세트 준비", owner: "hq", offset: -14, storeType: "테이블형", detail: "포스앞 메뉴판(A4·자석 스탠드) · 대형 스탠드 메뉴판(A3) · 네임텍(스텐홀더) · sold out 자석 · 박스구성 안내(1/4/6구) · 품절·영업시간 안내(A4) · 세트 POP(시그니처/버라이어티/하프더즌)" },
  { phase: "D-2주차", group: "디자인물", title: "[포장형] 디자인물 세트 준비", owner: "hq", offset: -14, storeType: "포장형", detail: "포스앞 메뉴판(A4) · X배너(커피+도넛 세트 구성) · 네임텍 · sold out 자석 · 박스구성 안내(1/4/6구) · 품절·영업시간 안내(A4) · 세트 POP" },
  { phase: "D-1주차", group: "현장 점검", title: "대형기물 셋팅 확인", owner: "pt", offset: -7, storeType: null, detail: "추가 필요 품목 확인" },
  { phase: "D-1주차", group: "현장 점검", title: "소기물 입고 확인", owner: "pt", offset: -7, storeType: null, detail: "" },
  { phase: "D-1주차", group: "현장 점검", title: "발주품목 입고 확인", owner: "pt", offset: -7, storeType: null, detail: "부자재 · 생활용품 · 사무용품 · 청소용품" },
  { phase: "D-1주차", group: "현장 점검", title: "디자인물 확인·부착", owner: "pt", offset: -7, storeType: null, detail: "내용 재확인 후 부착" },
  { phase: "D-1주차", group: "현장 점검", title: "매장 청소", owner: "pt", offset: -7, storeType: null, detail: "" },
  { phase: "D-1주차", group: "현장 점검", title: "동선 체크·운영 시뮬레이션", owner: "both", offset: -7, storeType: null, detail: "홀: 웨이팅라인·테이블 배치 / 바: 기물·부자재·용품 배치 / 전체 운영 시뮬레이션" },
  { phase: "D-1주차", group: "등록·연동", title: "포털 위치 등록 (네이버·구글·카카오맵)", owner: "pt", offset: -10, storeType: null, detail: "업체등록 심사까지 약 1주 소요 — 늦지 않게 신청" },
  { phase: "D-1주차", group: "등록·연동", title: "전화·인터넷 설치 → POS 설치", owner: "pt", offset: -10, storeType: null, detail: "인터넷 개통 후 포스 설치 · 포스 계정정보 본사 공유" },
  { phase: "D-1주차", group: "등록·연동", title: "토스 POS 서비스코드 연결 · 워크스테이션 연동", owner: "hq", offset: -7, storeType: null, detail: "토스 POS 설정→서비스 연동→코드 입력 후 [연결하기] · 워크스테이션에서 merchantId 웹훅 자동 감지 → 키 저장 → 동기화 · 필요 시 1·3·5년 수동 백필" },
  { phase: "D-1주차", group: "등록·연동", title: "배달 앱 등록 (쿠팡이츠·배민)", owner: "pt", offset: -7, storeType: null, detail: "이미지·메뉴 등록 · 계정정보 공유" },
  { phase: "D-1주차", group: "등록·연동", title: "(백화점/몰 입점 시) 식자재 보관·관리 교육", owner: "pt", offset: -7, storeType: null, detail: "백화점/몰 기준 식자재 보관·관리법 확인 — 해당 없으면 완료 처리" },
  { phase: "D-1주차", group: "홍보", title: "인스타그램 오픈 포스터 업로드", owner: "hq", offset: -7, storeType: null, detail: "외부 부착물 필요 시 운영팀 출력 문의" },
  { phase: "D-1주차", group: "운영 준비", title: "스케줄 공유", owner: "pt", offset: -7, storeType: null, detail: "" },
  { phase: "D-1주차", group: "운영 준비", title: "도넛 초도 발주", owner: "pt", offset: -8, storeType: null, detail: "오픈 7~10일 전, 지정 납품처에 수량 발주 요청" },
  { phase: "D-1주차", group: "운영 준비", title: "소통 창구 초대 (슬랙·구글시트)", owner: "hq", offset: -7, storeType: null, detail: "올페 가맹본부 워크스페이스 초대" },
  { phase: "D-1주차", group: "운영 준비", title: "워크스테이션 점주 접속코드 발급·안내", owner: "hq", offset: -7, storeType: null, detail: "설정 → 점주 접속코드 발급 → 마감·발주 사용법 안내" },
  { phase: "D-DAY", group: "오픈 전", title: "스텝 스케줄링·단톡방 생성", owner: "pt", offset: 0, storeType: null, detail: "" },
  { phase: "D-DAY", group: "오픈 전", title: "근무인원 체크", owner: "pt", offset: 0, storeType: null, detail: "매장 운영시간에 맞춰 인원 분배" },
  { phase: "D-DAY", group: "오픈 전", title: "메뉴 퀄리티 테스트", owner: "pt", offset: 0, storeType: null, detail: "오픈 전 직원 시식 진행 · 이상 있을 시 운영팀에 전달" },
  { phase: "D-DAY", group: "오픈 전", title: "오픈 업무 리스트 점검", owner: "pt", offset: 0, storeType: null, detail: "" },
  { phase: "D-DAY", group: "마감 후", title: "입고량 확인·업무 보고", owner: "pt", offset: 0, storeType: null, detail: "" },
  { phase: "D-DAY", group: "마감 후", title: "마감 업무 리스트 점검", owner: "pt", offset: 0, storeType: null, detail: "" },
  { phase: "D-DAY", group: "마감 후", title: "고객 피드백 체크", owner: "pt", offset: 0, storeType: null, detail: "" },
  { phase: "D-DAY", group: "마감 후", title: "판매량 확인·업무 보고", owner: "pt", offset: 0, storeType: null, detail: "워크스테이션 매출현황 자동 집계 대조" },
];
